spring:
  profiles:
    active: "local"
#        active: "dev"
  mvc:
    async:
      request-timeout: -1
  application:
    name: maumAcademy

  datasource:
    url: jdbc:mysql://localhost:3307/maumacademy
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 365214
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

hq:
  tokenReqPath: /hq/oauth/token
  logoutPath: /hq/oauth/deleteToken