spring:
  profiles:
    active: "local"
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
  resources:
    static-locations: file:C:/Users/smpar/Desktop/maum/mediaAtt/, classpath:/static


  mvc:
    async:
      request-timeout: -1
  application:
    name: maumAcademy

  datasource:
    url: jdbc:mysql://us-cdbr-east-04.cleardb.com/heroku_ead0d14e7ff9aa3
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bfda0896dfbd0f
    password: 9faba9b3
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  error:
    path: /error
    whitelabel:
      enabled: false
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

hq:
  tokenReqPath: /hq/oauth/token
  logoutPath: /hq/oauth/deleteToken