spring:
  profiles: local
  resources:
    static-locations: file:C:/Users/smpar/Desktop/mediaAtt/, classpath:/static
  mvc:
    async:
      request-timeout: -1
  application:
    name: maumAcademy

  datasource:
    url: jdbc:mysql://localhost:3306/maumacademy
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Park-sang1
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

maumAcademy:
  url: http://localhost:8080