spring:
  profiles: dev
  resources:
    static-locations: file:/home/ubuntu/mediaAtt/, classpath:/static
  mvc:
    async:
      request-timeout: -1
  application:
    name: maumAcademy


  datasource:
    url: jdbc:mysql://canada-tts.c4jrgbteu2g3.ca-central-1.rds.amazonaws.com/maumacademy
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: minds
    password: msl1234~
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


url:
  maum-ai: https://maum.ai
  hq: https://sso.maum.ai
  maumAcademy: https://maumacademy.maum.ai
  mail-maum-ai: https://maum.ai

sso:
  client-id: maumAcademy
  scope: read_profile
  callback: https://maumacademy.maum.ai/auth/callback

maumAcademy:
  url:  https://maumacademy.maum.ai